/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./kont.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone_5.geometry}
        material={materials.Troy}
        position={[-0.01442248, 0.13661691, 0.06421973]}
        rotation={[-0.73928573, 0, 0]}
        scale={0.00070893}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_1.geometry}
        material={materials["Champion 1"]}
        position={[-0.04586639, 0.17230632, -0.04911825]}
        rotation={[-2.09304969, -0.00062693, -0.18261894]}
        scale={[0.00060158, 0.00060158, 0.00006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Champion}
        position={[0.02563644, 0.17893223, -0.03769596]}
        rotation={[-2.09304969, -0.00062693, -0.18261894]}
        scale={[0.00060158, 0.00060158, 0.00006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_1.geometry}
        material={materials["Fresh Scent 1"]}
        position={[-0.12592591, 0.09186367, -0.0203396]}
        rotation={[-1.75840683, -0.01726309, 0.09067957]}
        scale={[0.00001821, 0.0003, 0.00137439]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_1_1.geometry}
        material={materials["Fresh Scent"]}
        position={[0.10991693, 0.09539655, -0.01092717]}
        rotation={[-1.75919009, 0, 0]}
        scale={[0.00001821, 0.0003, 0.00137439]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Sphere_7_-_baked_2"].geometry}
        material={materials["Evil Eye 8"]}
        position={[0.01606522, 0.10818225, 0.00569468]}
        rotation={[-Math.PI / 2, 0, -0.13858673]}
        scale={0.00080983}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Sphere_7_-_baked"].geometry}
        material={materials["Evil Eye 6"]}
        position={[-0.05018884, 0.10480236, -0.00048317]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.00080983}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_8.geometry}
        material={materials["Evil Eye 10"]}
        position={[0.01607303, 0.18282511, 0.0094824]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.0001917, 0.0001917, 0.00003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_7.geometry}
        material={materials["Evil Eye 9"]}
        position={[-0.04969613, 0.18136633, 0.00994145]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.0001917, 0.0001917, 0.00003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_3.geometry}
        material={materials["Evil Eye 2"]}
        position={[0.01574931, 0.10449147, 0.00930641]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.00080983}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_1.geometry}
        material={materials["Evil Eye"]}
        position={[-0.0488522, 0.10236211, 0.00930641]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.00080983}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box.geometry}
        material={materials.Kingdom}
        position={[-0.00951061, 0.16056018, -0.03715743]}
        rotation={[-2.09304969, -0.00062693, -0.18261894]}
        scale={[0.0017, 0.0008, 0.0002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone_1.geometry}
        material={materials.Sienna}
        position={[0.09674774, 0.08501281, -0.05038945]}
        rotation={[-Math.PI, 0.53599807, 0]}
        scale={[0.00049661, 0.00049661, 0.00049661]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone_2.geometry}
        material={materials["Andorra 1"]}
        position={[0.06000263, 0.08573414, -0.01607906]}
        rotation={[Math.PI, 0.66736096, -1.74532925]}
        scale={[0.001, 0.001, 0.001]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone_4.geometry}
        material={materials["Andorra 3"]}
        position={[-0.0831034, 0.08778472, -0.01672115]}
        rotation={[Math.PI, -0.11623266, -1.74532925]}
        scale={[0.00071, 0.00071, 0.00071]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone_3.geometry}
        material={materials["Andorra 2"]}
        position={[-0.09049385, 0.08573414, -0.07453082]}
        rotation={[Math.PI, -0.02762866, -1.74532925]}
        scale={[0.00048444, 0.00048444, 0.00048444]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone.geometry}
        material={materials.Andorra}
        position={[-0.07907225, 0.08573414, -0.05168761]}
        rotation={[Math.PI, -0.15956387, -1.74532925]}
        scale={[0.00071512, 0.00071512, 0.00071512]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials.Bilbao}
        position={[-0.01066442, 0, 0.0255618]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.00260332, 0.00214592, 0.00173846]}
      />
    </group>
  );
}

useGLTF.preload("./kont.glb");